

MACRO_TAKE_UP_KEYCH0 MACRO
	STX <WB_KEYCH_CODE	;SAVE THE KEYCODE
	LDA #0FH
	TRB <WB_KEYDLY	;CLR
	LDA #00010001B
	TRB <WB_KEY_FLAG	;CLR FLAG
	ENDM
	
MACRO_TAKE_UP_KEYCH1 MACRO
	STX <WB_KEYCH_CODE+1	;SAVE THE KEYCODE
	LDA #0F0H
	TRB <WB_KEYDLY	;CLR
	LDA #00100010B
	TRB <WB_KEY_FLAG	;CLR FLAG
	ENDM

;MACRO_TAKE_UP_KEYCH2 MACRO
;	STX <WB_KEYCH_CODE+2	;SAVE THE KEYCODE
;	LDA #0FH
;	TRB <WB_KEYDLY+1	;CLR
;	LDA #01000100B
;	TRB <WB_KEY_FLAG	;CLR FLAG
;	ENDM


	

