
;========================
;	CHKMKEY_RAM.H
;========================
;C_SCANKEY_4CH_LP EQU	0
;C_SCANKEY_4CH_LN	EQU	0


;C_MKEYCH_MAX	EQU	0; MAX = 4;if GND as output: should be '1'

;C_MKEYCH_MAX_REV EQU 0

;C_CHKMKEY_GND_AS_OP EQU 0

;C_LED_MATRIX_CONFIG		EQU		0
;C_CHK_KEY_SHARE_LED_EN EQU	0



;C_WLED_EXIT	EQU	0


;===============================
; special function
;================================
;==============================
;MOTOR PWM
;==============================
;C_M1_PWM_EN	EQU	0


;=============================
;	LED_FSH_CTRL_RAM.H
;==============================
;C_LIGHT_FSH_ENABLE EQU	0
;C_DRUMLED_ENABLE	EQU	0;按鼓对应的LED亮，按时间控制亮灭
;==============================
;WIPER
;==============================
;C_WIPER_EN	EQU	0
;C_CHKPOS_EN 	EQU	0

;==========================
;	CHK_MODE.ASM
;==========================
;C_CHKMODE_EN	EQU	0


;==============================================

;C_PWON_SLEEP_EN EQU	0



;========================
;	EQU_RAM.H
;========================





;========================
;	AUTOSLEEP_RAM.H
;========================


;C_LEDS_FLOW_USE_CNT0 EQU	0


