

;====================================
;	3 PWMS
;====================================

L_PWM_INIT:
; TM1: 0.5MS/0.626ms
	
	RTS

L_COLOR_START:
; TMG1: 0.5MS
	M_PWM0_OFF
	M_PWM1_OFF
	M_PWM2_OFF
	STZ	LED_TBL_PT
	STZ	LED_TBL_PT+1

	JSR	LOAD_3LED_TBL
	
	PWM0_ENABLE

	LDA	#C_PWM_SPEED
	STA	<PWM_SPEED
	
	RTS

L_COLOR_STOP:
	
	PWM0_DISABLE

	M_PWM0_OFF
	M_PWM1_OFF
	M_PWM2_OFF
	
	RTS

;======================================
LOAD_3LED_TBL:
	PHY
	LDA	#.LOW.T3LED_TABLE0
	STA	<P0_TEMP0
	LDA	#.HIGH.T3LED_TABLE0
	STA	<P0_TEMP0+1

	STZ	<REG_EA
	LDA	<LED_TBL_PT
	ASL	A
	ROL	<REG_EA
	ASL	A
	ROL	<REG_EA
	CLC
	ADC	<P0_TEMP0
	STA	<P0_TEMP0
	LDA	<REG_EA
	ADC	<P0_TEMP0+1
	STA	<P0_TEMP0+1
	
	LDY	#0
	LDA	(<P0_TEMP0),Y
	STA	<PWM0_LEVEL
	BEQ	L_PWM_SOLVE_S010
	M_PWM0_ON
;	BRA	L_PWM_SOLVE_S011
L_PWM_SOLVE_S010:
;	M_PWM0_OFF
;L_PWM_SOLVE_S011:
	INY
	LDA	(<P0_TEMP0),Y
	STA	<PWM1_LEVEL
	BEQ	L_PWM_SOLVE_S020
	M_PWM1_ON
;	BRA	L_PWM_SOLVE_S021
L_PWM_SOLVE_S020:
;	M_PWM1_OFF
;L_PWM_SOLVE_S021:
	INY
	LDA	(<P0_TEMP0),Y
	STA	<PWM2_LEVEL
	BEQ	L_PWM_SOLVE_S030
	M_PWM2_ON
;	BRA	L_PWM_SOLVE_S031
L_PWM_SOLVE_S030:
;	M_PWM2_OFF
;L_PWM_SOLVE_S031:
	PLY
	RTS
;======================
; USE: Y
;T=500US
;in main loop
;========================
L_PWM_SOLVE_SUB_END:
	RTS

L_PWM_SOLVE_SUB:
; 3led pwm
;0;0-31
	
	LDA	#C_BIT0
	BIT	PWM_FLAG
	BEQ	L_PWM_SOLVE_SUB_END
;PWM0 ENABLE
	INC	<PWM_CNT ; 0-31
	LDA	<PWM_CNT
	CMP	#C_MAX_LEVEL
	BNE	L_PWM_SOLVE_S100
	STZ	<PWM_CNT
;1 PWM LEVEL END
	INC	<PWM_SPEED
	BNE	L_PWM_SOLVE_S190
	LDA	#C_PWM_SPEED
	STA	<PWM_SPEED

	INC	<LED_TBL_PT
	BNE	L_PWM_SOLVE_S001
	INC	<LED_TBL_PT+1
L_PWM_SOLVE_S001:

	LDA	<LED_TBL_PT+1
	CMP	#.HIGH.C_T3LED_TABLE0_CNT
	BNE	L_PWM_SOLVE_SUB_S010
	LDA	<LED_TBL_PT
	CMP	#.LOW.C_T3LED_TABLE0_CNT
	BNE	L_PWM_SOLVE_SUB_S010

;loop: restart the pattern
	LDA	#10
	STA	<LED_TBL_PT
	STZ	<LED_TBL_PT+1
	
L_PWM_SOLVE_SUB_S010:
	
	JMP	LOAD_3LED_TBL
	
L_PWM_SOLVE_S190:
	LDA	<PWM0_LEVEL
	BEQ	L_PWM_SOLVE_S191
	M_PWM0_ON
;	BRA	L_PWM_SOLVE_S192
L_PWM_SOLVE_S191:
;	M_PWM0_OFF
;L_PWM_SOLVE_S192:
	LDA	<PWM1_LEVEL
	BEQ	L_PWM_SOLVE_S193
	M_PWM1_ON
;	BRA	L_PWM_SOLVE_S194
L_PWM_SOLVE_S193:
;	M_PWM1_OFF
;L_PWM_SOLVE_S194:
	LDA	<PWM2_LEVEL
	BEQ	L_PWM_SOLVE_S195
	M_PWM2_ON
;	BRA	L_PWM_SOLVE_S196
L_PWM_SOLVE_S195:
;	M_PWM2_OFF
;L_PWM_SOLVE_S196:
	RTS
	
L_PWM_SOLVE_S100:
	LDA	<PWM_CNT
	CMP	<PWM0_LEVEL
	BNE	L_PWM_SOLVE_S110
	M_PWM0_OFF
L_PWM_SOLVE_S110:
	LDA	<PWM_CNT
	CMP	<PWM1_LEVEL
	BNE	L_PWM_SOLVE_S120
	M_PWM1_OFF
L_PWM_SOLVE_S120:
	LDA	<PWM_CNT
	CMP	<PWM2_LEVEL
	BNE	L_PWM_SOLVE_S200
	M_PWM2_OFF
L_PWM_SOLVE_S200:
	RTS
;


                              